package utils

import (
	"os"
	"path/filepath"
	"strings"
	"sync"

	"ytdpldownloader/runner"

	"github.com/charmbracelet/log"
	"gopkg.in/yaml.v3"
)

// Utility package

type YtdplProbe []struct {
	FormatID   string  `json:"format_id"`
	FormatNote string  `json:"format_note"`
	Ext        string  `json:"ext"`
	Protocol   string  `json:"protocol"`
	Acodec     string  `json:"acodec"`
	Vcodec     string  `json:"vcodec"`
	URL        string  `json:"url"`
	Width      int     `json:"width"`
	Height     int     `json:"height"`
	Fps        float64 `json:"fps"`
	Rows       int     `json:"rows,omitempty"`
	Columns    int     `json:"columns,omitempty"`
	Fragments  []struct {
		URL      string  `json:"url"`
		Duration float64 `json:"duration"`
	} `json:"fragments,omitempty"`
	AudioExt       string  `json:"audio_ext"`
	VideoExt       string  `json:"video_ext"`
	Vbr            int     `json:"vbr"`
	Abr            int     `json:"abr"`
	Tbr            any     `json:"tbr"`
	Resolution     string  `json:"resolution"`
	AspectRatio    float64 `json:"aspect_ratio"`
	FilesizeApprox any     `json:"filesize_approx"`
	HTTPHeaders    struct {
		UserAgent      string `json:"User-Agent"`
		Accept         string `json:"Accept"`
		AcceptLanguage string `json:"Accept-Language"`
		SecFetchMode   string `json:"Sec-Fetch-Mode"`
	} `json:"http_headers"`
	Format             string  `json:"format"`
	Asr                int     `json:"asr,omitempty"`
	Filesize           int     `json:"filesize,omitempty"`
	SourcePreference   int     `json:"source_preference,omitempty"`
	AudioChannels      int     `json:"audio_channels,omitempty"`
	Quality            float64 `json:"quality,omitempty"`
	HasDrm             bool    `json:"has_drm,omitempty"`
	Language           any     `json:"language,omitempty"`
	LanguagePreference int     `json:"language_preference,omitempty"`
	Preference         any     `json:"preference,omitempty"`
	DynamicRange       any     `json:"dynamic_range,omitempty"`
	Container          string  `json:"container,omitempty"`
	AvailableAt        int     `json:"available_at,omitempty"`
	DownloaderOptions  struct {
		HTTPChunkSize int `json:"http_chunk_size"`
	} `json:"downloader_options,omitempty"`
}

type AutoGenerated []struct {
	FormatID   string  `yaml:"format_id"`
	FormatNote string  `yaml:"format_note"`
	Ext        string  `yaml:"ext"`
	Protocol   string  `yaml:"protocol"`
	Acodec     string  `yaml:"acodec"`
	Vcodec     string  `yaml:"vcodec"`
	URL        string  `yaml:"url"`
	Width      int     `yaml:"width"`
	Height     int     `yaml:"height"`
	Fps        float64 `yaml:"fps"`
	Rows       int     `yaml:"rows,omitempty"`
	Columns    int     `yaml:"columns,omitempty"`
	Fragments  []struct {
		URL      string  `yaml:"url"`
		Duration float64 `yaml:"duration"`
	} `yaml:"fragments,omitempty"`
	AudioExt       string      `yaml:"audio_ext"`
	VideoExt       string      `yaml:"video_ext"`
	Vbr            int         `yaml:"vbr"`
	Abr            int         `yaml:"abr"`
	Tbr            interface{} `yaml:"tbr"`
	Resolution     string      `yaml:"resolution"`
	AspectRatio    float64     `yaml:"aspect_ratio"`
	FilesizeApprox interface{} `yaml:"filesize_approx"`
	HTTPHeaders    struct {
		UserAgent      string `yaml:"User-Agent"`
		Accept         string `yaml:"Accept"`
		AcceptLanguage string `yaml:"Accept-Language"`
		SecFetchMode   string `yaml:"Sec-Fetch-Mode"`
	} `yaml:"http_headers"`
	Format             string      `yaml:"format"`
	Asr                int         `yaml:"asr,omitempty"`
	Filesize           int         `yaml:"filesize,omitempty"`
	SourcePreference   int         `yaml:"source_preference,omitempty"`
	AudioChannels      int         `yaml:"audio_channels,omitempty"`
	Quality            float64     `yaml:"quality,omitempty"`
	HasDrm             bool        `yaml:"has_drm,omitempty"`
	Language           interface{} `yaml:"language,omitempty"`
	LanguagePreference int         `yaml:"language_preference,omitempty"`
	Preference         interface{} `yaml:"preference,omitempty"`
	DynamicRange       interface{} `yaml:"dynamic_range,omitempty"`
	Container          string      `yaml:"container,omitempty"`
	AvailableAt        int         `yaml:"available_at,omitempty"`
	DownloaderOptions  struct {
		HTTPChunkSize int `yaml:"http_chunk_size"`
	} `yaml:"downloader_options,omitempty"`
}

type AppData struct {
	YTdplBinPath   string `yaml:"ytdlp_bin_path"`
	FFmpegBinPath  string `yaml:"ffmpeg_bin_path"`
	FFprobeBinPath string `yaml:"ffprobe_bin_path"`
	DownloadDir    string `yaml:"download_dir"`
	MaxConcurrent  int    `yaml:"max_concurrent"`
	DBPath         string `yaml:"db_path"`
}

func loadDefaultConfig() AppData {
	return AppData{YTdplBinPath: "", FFmpegBinPath: "", DownloadDir: filepath.Join(".", "downloads"), MaxConcurrent: 5, DBPath: filepath.Join(".", "badgerDB")}
}

func LoadConf() AppData {
	log.Debug("Reading appConf.yaml")

	data, err := os.ReadFile("./appConf.yaml")
	if err != nil {
		if os.IsNotExist(err) {
			log.Info("Config not found. Creating default appConf.yaml")
			cfg := loadDefaultConfig()
			data, _ := yaml.Marshal(cfg)

			if err = os.WriteFile("./appConf.yaml", data, 0o644); err != nil {
				log.Printf("Failed to write config file: %v", err)
			}
			log.Warn("Exiting app now\nPlease update the binary location in appConf.yaml")
			os.Exit(0)
		}

		log.Printf("Failed to read config: %v", err)
		return loadDefaultConfig()
	}

	cfg := loadDefaultConfig()

	if err := yaml.Unmarshal(data, &cfg); err != nil {
		log.Printf("Failed to parse config: %v", err)
		return loadDefaultConfig()
	}

	return cfg
}

func CheckBin(data AppData) {
	log.Info("Using yt-dpl path:\t" + data.YTdplBinPath)
	log.Info("Using FFmpeg path:\t" + data.FFmpegBinPath)
	log.Info("Using FFprobe path:\t" + data.FFprobeBinPath)
	ytdplver, stderryt := runner.Run(data.YTdplBinPath + " --version")
	ffmpegver, stderrffmpeg := runner.Run(data.FFmpegBinPath + " -version")
	ffprobever, stderrffprobe := runner.Run(data.FFprobeBinPath + " -version")
	var wg sync.WaitGroup
	// var ytOut, ytErr, ffOut, ffErr, fpOut, fpErr []byte
	wg.Add(3)
	go func() {
		defer wg.Done()
		errstr := string(<-stderryt)
		log.Debug("YT DPL version", string(<-ytdplver))
		if len(strings.TrimSpace(errstr)) > 0 {
			log.Error("[Warn]YT DPL has an error\n:", "yt_dpl error\t:", errstr)
		}
	}()
	go func() {
		defer wg.Done()
		errstr := string(<-stderrffmpeg)
		log.Debug("FFmpeg version", string(<-ffmpegver))
		if len(strings.TrimSpace(errstr)) > 0 {
			log.Error("[Warn]FFMPEG has an error\n:", "ffmpeg error\t:", errstr)
		}
	}()
	go func() {
		defer wg.Done()
		errstr := string(<-stderrffprobe)
		log.Debug("FFprobe version", string(<-ffprobever))
		if len(strings.TrimSpace(errstr)) > 0 {
			log.Error("[Warn]FFPROBE has an error\n:", "ffprobe error\t:", errstr)
		}
	}()
	wg.Wait()
}
